### PR TITLE
One half of roster changes

### PR DESCRIPTION
**Pull request by kirubarajan**
- Create/Update/Delete half of new roster changes
- Deleted `Fixed Sizes.zip` from static images folder (seemed to be duplicated but unsure of whether it was necessary)
- Waiting on @KNWR for the second half (can merge into this branch or to master)

### CODE REVIEW

**Comment by kirubarajan** [comment]
Additionally removed all code-base references to `national` and replaced them with `hq`.

**Comment by VinaiRachakonda** [comment]
Looks good. @KNWR  can you actually just merge into this branch when you're done with your work so we can see what the final site looks like.

**Comment by VinaiRachakonda** [comment]
Actually a couple of mistakes here @kirubarajan. Some people that are in NYC are in the Philly bracket i.e: Lola, Isabela, Chris Shei, David Dellal.

**Comment by kirubarajan** [comment]
How about now?

**Comment by kirubarajan** [comment]
Looks good to me, but still unclear if the original csv was correct so I'd wait on merging until Vinai takes a look.

**Comment by KNWR** [comment]
Yeah 100% - ex. Casey should also be removed from HQ and set as alum

**Pull request merged**
